baseURL = "https://hamletv.github.io/"
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
title = "Mozilla A11y"
theme = "minimal"
googleAnalytics = ""

[params]
  author = "Hamlet Villa"
  description = "Web Acessibility: Improving image content access for screen reader users."
  githubUsername = "hamletv"
  font = "Raleway"
  accent = "green"
  showBorder = true
  backgroundColor = "white"
  highlight = true
  highlightStyle = "solarized-dark"

[[menu.main]]
  url = "/"
  name = "Home"
  weight = 1

[[menu.main]]
  url = "/posts/"
  name = "Posts"
  weight = 2

[[menu.main]]
  url = "/project/"
  name = "Projects"
  weight = 3

[[menu.icon]]
  url = "mailto:hamlet.villa@gmail.com"
  name = "envelope-o"
  weight = 1

[[menu.icon]]
  url = "https://github.com/hamletv/"
  name = "github"
  weight = 2

[[menu.icon]]
  url = "https://twitter.com/hamlet_villa/"
  name = "twitter"
  weight = 3

[[menu.icon]]
  url = "https://www.linkedin.com/in/hamlet-villa-1552186/"
  name = "linkedin"
  weight = 4

[[menu.icon]]
  url = "https://www.stackoverflow.com/6257511/hamlet/"
  name = "stack-overflow"
  weight = 5
